### ISSUE TITLE
Idea: automatically save a pointer to the .git commit hash

### ISSUE THREAD

**Issue by andrewjong** [kourai-research/pytorch-boilerplate#5]
Every time an experiment is run, output a file that points to the code's commit number.

Of course, this depends on not rebasing / changing history. Could provide an additional option that says: instead of pointing to a commit, make a .zip archive of all the source files.

**Comment by SBoulanger** [comment]
What is the biggest reason for a feature like this? In what scenarios are you needing to do something with a previous experiment's source code?

**Comment by andrewjong** [comment]
When seeing the results of the experiment, sometimes want to see which code generated those results. Perhaps an implementation of a network changed in a future version; if some results don't make sense, you can look back the code which generated it.

**Comment by andrewjong** [comment]
Actually I found out wandb does this already!! Super cool

**Comment by SBoulanger** [comment]
Cool :) I knew they stored the trian script, didnt know to what extent they save your project
